flora-pm/flora-server

.gitignore, app/cli/CoverageReport.hs, app/cli/Main.hs, flora.cabal, src/Flora/Model/Category.hs
Adds a `Map` that serves to map the most common Hackage categories to canonical Flora category slugs and tags. Also includes a cli utility for downloading the package index and checking what coverage the mapping provides across all of Hackage.
=> Add category mapping and coverage report

.github/workflows/ci.yml, shell.nix, src/FloraWeb/Server/Pages.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Templates.hs, src/FloraWeb/Templates/Error.hs, src/FloraWeb/Templates/Layout/App.hs, src/FloraWeb/Templates/Types.hs
This PR removes the usage of a `Map Text Text` to inject values in a template (the "assigns" pattern) and goes with a record that has a default value instead.
=> Remove the usage of a Map to store template variables

nix/pkgs.nix
This disables running tests for pg-entity and pg-transacts.
I think both these testsuites want postgres to be available, 
which won't work in a nix build container.
I also fixed cabal issues for pcre2 and optics-core.
I don't know how to solve the lucid one (without modifying the cabal file)
Note that this targets the `fix-nix` branch.
=> disable tests for pg-entity and pg-transacts

Makefile
this will make it run before doing asset build.
I couldn't figure this out yesterday at night,
this should make that easier.
=> Add assets deps dependency for asset build in makefile

default.nix, nix/pkgs.nix
I think that version set before wasn't used at all.
I'm not sure why that {} is used if not for evaluating cabal.
This is a little ugly, but so is nix in general.
(note this targets the add-user-sessions branch again).
=> Set cabal version in default.nix instead of pkgs.

.dockerignore, .github/workflows/ci.yml, Dockerfile, Makefile, README.md, database.env, default.nix, docker-compose.yml, environment.docker.sh, environment.sh, nix/pin.nix, nix/pkgs.nix, scripts/start-tmux.sh, shell.nix
This PR brings in a Docker-based workflow that requires minimal pre-requisites on the host machine. Inside Docker, the build is handled by Nix.
=> Docker setup

assets/css/app.css, src/FloraWeb/Templates/Layout/App.hs
(Also works on light mode)
- Menu working with mouse or keyboard
- Closable using the escap key
- interactive `aria-expanded` attribute to vocalize menu states (opened/closed)
=> Improve user menu interface

nix/cabal2nix/http-client.nix, nix/pkgs.nix, nix/test.nix
(note this targets add-user-session branch)
this is the old way of calling packages, I just ran cabal2nix
and put the result http-client.nix file.
this prevents the cycle:
nix'es callHackage uses cabal2nix
which uses http-client apparently.
=> Upgrade http client

Makefile
/bin/bash isn't guaranteed to exist by POSIX, and in fact does not exist
on NixOS. /usr/bin/env is guaranteed, on the other hand. This uses
whatever bash is on PATH, which on more conventional Linuces will
probably still be /bin/bash.
This shouldn't actually change anything wrt flora itself! Just making the build a little more portable.
=> Makefile: use /usr/bin/env bash rather than /bin/bash

.github/workflows/ci.yml, Makefile, assets/tailwind.config.js, flora.cabal, migrations/20211106003401_create_packages.sql, src/Flora/Import/Package.hs, src/Flora/Model/Category/Query.hs, src/Flora/Model/Package/Query.hs, src/Flora/Search.hs, src/FloraWeb/Routes/Pages.hs, src/FloraWeb/Routes/Pages/Packages.hs, src/FloraWeb/Server/Pages.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Session.hs, src/FloraWeb/Templates/Layout/App.hs, src/FloraWeb/Templates/Packages/Listing.hs, src/FloraWeb/Templates/Pages/Categories/Index.hs, src/FloraWeb/Templates/Pages/Home.hs, src/FloraWeb/Templates/Pages/Search.hs, test/Flora/PackageSpec.hs, test/fixtures/Cabal/Win32.cabal
=> Starting the V1 search engine

assets/esbuild.config.js, assets/js/autoreload.js, cabal.project, flora.cabal, src/FloraWeb/Autoreload.hs, src/FloraWeb/Client.hs, src/FloraWeb/Routes.hs, src/FloraWeb/Server.hs, src/FloraWeb/Server/Auth/Types.hs, src/FloraWeb/Templates.hs
This PR implements a websocket endpoint that keeps the browser updated about the state of the backend. If the backend restarts, then the frontend client triggers the reloading of the page.
=> Automatic reload of frontend

Dockerfile
The image from which the image is being built has older version of cabal. 
So running `cabal update` explicitly just before the `cabal build` fixes the issue with cabal failing to construct the dependency tree because of unknown package versions.
=> chore: fix docker build

src/FloraWeb/Templates/Pages/Packages.hs
When viewing a single package, make the sidebars on both side of the readme stick to the top of screen, so essential data is remains accessible when scrolling through long READMEs. This doesn't affect the page on mobile displays.
Here are before and after videos (don't mind the placeholder text)
https://user-images.githubusercontent.com/8615241/184170514-cad85391-4ead-475d-a027-d78d4e42d134.mov
https://user-images.githubusercontent.com/8615241/184170870-6cb3a23d-95b3-4b4c-813a-6a3a0e3b984f.mov
=> Make package sidebars sticky

assets/css/app.css, src/FloraWeb/Templates/Pages/Packages.hs
=> Harmonise the size of the package title and version in mobile view

migrations/20211106123053_create_releases.sql, src/Flora/Import/Package.hs, src/Flora/Model/Release/Query.hs, src/Flora/Model/Release/Types.hs, src/Flora/Model/Release/Update.hs, src/Flora/OddJobs.hs, src/FloraWeb/Server/Pages/Admin.hs
Automatically schedule readme fetching job after index import.
This PR also adds more granularity for the README import state, which means that we can differentiate between releases for which there is no README attached in Hackage, and those for which the README simply hasn't been imported yet.
=> Automatically schedule readme fetching job after index import

src/Flora/OddJobs.hs
Fix #200
Some packages were removed from the index. Hackage returns a 410 Gone status when trying to query their resources.
=> Treat Gone Readmes as Inexistent

CHANGELOG.md, src/FloraWeb/Server/Pages/Packages.hs
Add OpenGraph metadata in package pages
=> [FLORA-216] Add OpenGraph metadata in package pages

.github/mergify.yml, CHANGELOG.md, deployment/flora.nginx, src/FloraWeb/Server.hs, src/FloraWeb/Server/Auth.hs, src/FloraWeb/Server/Auth/Types.hs
This PR fixes #224 by fetching a request ID from the web proxy (or generate one locally), and injects it in log statement metadata. It is stored in the Session.
=> Generate request ID in Nginx

.github/mergify.yml, .github/workflows/check-flora-tickets-in-prs.yaml, .github/workflows/check-ticket-in-prs.sh
This PR brings a new Github Action that checks for the `[FLORA-XXX] | [NO-ISSUE]` pattern in PR titles and git commit.
=> [FLORA-226] Enforce ticket in PR title or first commit

CHANGELOG.md, src/Flora/OddJobs.hs
Enable the same commonmark extensions that Hackage does
=> [FLORA-205] Enable the use of markdown extensions

CHANGELOG.md, environment.test.sh, ghc-tags.yaml, migrations/20211113195849_create_dependents.sql, test/Flora/PackageSpec.hs, test/Flora/TestUtils.hs, test/Main.hs
Fix the `dependents` view to include other namespaces
=> [FLORA-255] Fix the `dependents` view to include other namespaces

CHANGELOG.md, assets/css/compiler-badge.css, assets/css/styles.css, src/FloraWeb/Templates/Pages/Packages.hs
The title of a page is brought to 2rem instead of 3 on smaller screens
=> [NO-ISSUE] Fix package title size in smaller screens

CHANGELOG.md, src/web/FloraWeb/Components/Header.hs, src/web/FloraWeb/Server/Pages/Packages.hs, src/web/FloraWeb/Templates/Types.hs
Adds the robots noindex meta tag on package pages unless they're explicitly versioned.
=> [FLORA-132] Only index versionless package pages

.github/workflows/check-flora-tickets-in-prs.yaml, assets/css/styles.css, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Requirement.hs, src/web/FloraWeb/Components/PackageListItem.hs, src/web/FloraWeb/Server/Pages/Packages.hs, src/web/FloraWeb/Templates/Packages.hs, src/web/FloraWeb/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs
Expands the dependencies page to list the dependencies of each components, using the HTML details tag.
Opening is as draft for now: the package page might want to be changed to always have a link to the full components dependencies page; probably want the number of each components dependencies in the summary tag; and one of the tests needs updating. I'm relatively inexperienced with HTML and CSS, so do say if there are better approaches for this!
Attached two screenshots for what it looks like so far.
=> [FLORA-142] Add components to dependencies page

CHANGELOG.md, assets/css/styles.css, design/stories/package-list--item.stories.js, src/web/FloraWeb/Components/PackageListItem.hs, test/Flora/PackageSpec.hs, test/fixtures/Cabal/text-display.cabal
This PR reduces the space between packages in package listings. This allows us to use space more efficiently and make people scroll less.
=> [FLORA-354] Make package listings denser

flake.lock, flake.nix
The GitLab instance seems to have moved, leading to the `nix` commands failing. Or it's just temporarily down, but on https://horizon-haskell.net/ there's a new link that "just works".
Change the flake url to the new one, which is https://gitlab.horizon-haskell.net/package-sets/horizon-platform.
@locallycompact I just wanted to check out the repo and try something, and stumbled over this. You would probably know if this PR makes sense, that is, if that new url is correct as "the new home" for `horizon-platform`.
Note that I didn't use the same commit, but rather the latest one. I could of course change that, but everything seems to work just fine. Just let me know :)
=> [NO-ISSUE] Fix flake url for `horizon-platform`

docker-compose.yml
I tried out the Docker setup, but it's using `postgres`, that is, `postgres:latest`, which downloads the database in major version 15. The readme still mentions that version 14 is used, so I pinned it.
=> [NO-ISSUE] Pin the `postgres` Docker image to version 14

.github/mergify.yml, Dockerfile, Makefile, README.md, environment.docker.sh, scripts/start-tmux.sh
I did the following and also added some minor improvements to the whole Docker setup:
1. Pinned the base image: indeed using Ubuntu 22.04 was necessary for `souffle` to work/build.
2. Introduced docker `ARGS` to hopefully make future GHC upgrades easier for this setup.
3. Updated `cabal-install`, as it was incompatible in the default version 3.6.*.
4. Added the missing `ghcid`.
5. Rearranged and merged some Docker commands for slightly better caching and robustness.
6. Added `environment.docker.sh` due to `FLORA_DB_HOST` having to be set differently in the docker compose setup.
Other things:
- I had to do `yarn install` in the `start-tmux.sh` script, or otherwise the `make start-tmux` would crash with missing dependencies.
- Migrated from the deprecated, standalone `docker-compose` to the …
=> [FLORA-368] Upgrade and unbreak docker setup for GHC 9.4.4

CHANGELOG.md, assets/css/package.css, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Search.hs, src/web/FloraWeb/Components/PaginationNav.hs, src/web/FloraWeb/Links.hs, src/web/FloraWeb/Routes/Pages/Packages.hs, src/web/FloraWeb/Server/Pages/Packages.hs, src/web/FloraWeb/Templates/Pages/Packages.hs, src/web/FloraWeb/Templates/Pages/Search.hs, test/Flora/TemplateSpec.hs
As described in #219. I also added a link to the namespace in the package title; don't know if you want/like that, but I didn't know about `Servant.Links` before and wanted to try it out.
I have some remaining questions though:
1. Some `count*` functions in `Query.hs` filter for the `fully-imported` status, some don't. I wasn't sure which to pick, so left it out for now.
2. The new `showNamespaceHandler` is *very* similar to the `indexHandler` above, but I felt like "repeating" some easy steps or function is a deliberate choice when looking at some other code. Plus, extracting a function here would most likely mean having an `Eff` action as argument, which would require importing lots of stuff and IME not really make anything more flexible. How do you think about this?
3. …
=> [FLORA-219] Implement namespace browsing

.gitignore, flora.cabal, src/core/Flora/Model/Component/Types.hs, src/core/Flora/Model/Job.hs, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Model/Release/Query.hs, src/core/Flora/Model/Release/Types.hs, src/datatypes/Distribution/Orphans.hs, src/datatypes/Distribution/Orphans/CompilerFlavor.hs, src/datatypes/Distribution/Orphans/ConfVar.hs, src/datatypes/Distribution/Orphans/PackageFlag.hs, src/datatypes/Distribution/Orphans/Version.hs, src/web/FloraWeb/API/Routes/Packages/Types.hs
This PR substitutes generic deriving of JSON instances that is too costly with Template Haskell deriving.
Generics are still demanding but Servant is the second next big consumer and there's no TH equivalent.
---
Before
---
After
=> [FLORA-420] Improve build performance

CHANGELOG.md, src/web/FloraWeb/Common/OpenSearch.hs, src/web/FloraWeb/Components/Header.hs
Match the "ShortName" field in the OpenSearch XML file with the "title" property in the link to the OpenSearch XML document in the head element. This complies with [Mozilla's OpenSearch description format page](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#autodiscovery_of_search_plugins) and results in the "add search engine" button disappearing as it should once Flora has been added.
Also, the OpenSearch description does not make any sense as it now matches the short name, whereas it should describe the search engine (Flora). As it is not relevant I've left it for now, but it should probably be changed to something more appropriate in the future.
=> [FLORA-198] Fix mismatching OpenSearch names

CHANGELOG.md, deployment/flora.nginx, src/web/FloraWeb/Pages/Routes.hs, src/web/FloraWeb/Pages/Server.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Templates/Error.hs
This PR configures the api. sub-domain and rejects queries to flora.pm/api.
=> [NO-ISSUE] Configure the API gateway

CHANGELOG.md, docs/docs/intro.md, docs/docs/namespaces.md
=> [FLORA-450] Add a guide for namespaces

.github/mergify.yml, CHANGELOG.md, assets/css/2-components/5-primary-search.css, assets/css/2-components/6-secondary-search.css, assets/css/3-screens/4-front-page.css, assets/css/styles.css, flora.cabal, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Search.hs, src/web/FloraWeb/Components/Icons.hs, src/web/FloraWeb/Components/MainSearchBar.hs, src/web/FloraWeb/Components/PaginationNav.hs, src/web/FloraWeb/Components/SlimSearchBar.hs, src/web/FloraWeb/Components/Utils.hs, src/web/FloraWeb/Links.hs, src/web/FloraWeb/Pages/Routes/Packages.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Pages/Home.hs, src/web/FloraWeb/Pages/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs
closes #388
supercedes #389
Original changes by @dylan-thinnes: 
> Reverse dependency lists (a.k.a dependents) can get huge, e.g. for the lens library, which makes pagination impractical. This implements a search bar in the reverse dependencies page.
=> [FLORA-388] Reverse depenencies search bar

CHANGELOG.md, docs/docs/intro.md, docs/docs/search.md, flora.cabal, scripts/run-tests.sh, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Search.hs, src/web/FloraWeb/Components/Navbar.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Server/Search.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Types.hs, test/Flora/PackageSpec.hs, test/Flora/SearchSpec.hs, test/Main.hs
This PR introduces modifiers for the search bar:
* `depends:<@namespace>/<packagename>` 
Shows the dependents page for a package
* `in:<@namespace> <packagename>`
Search for a package name in the specified namespace
* `in:<@namespace>`
List packages in a namespace
Also the "Show dependents" page will be implemented in these terms, and we'll get rid of the extraneous search bar.
=> [FLORA-35] Search bar modifiers

test/Main.hs
During test set-up, instead of dropping the whole database we are only selectively deleting data from the tables. The materialized views stay in place.
=> [NO-ISSUE] Delete data from test tables instead of dropping the DB

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, app/cli/DesignSystem.hs, assets/css/2-components/9-terminal-icon.css, assets/css/styles.css, docs/docs/search.md, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Search.hs, src/web/FloraWeb/Components/Icons.hs, src/web/FloraWeb/Components/PackageListItem.hs, src/web/FloraWeb/Pages/Server/Search.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Screens/Search.hs, test/Flora/PackageSpec.hs, test/Flora/SearchSpec.hs, test/Flora/TestUtils.hs
This PR introduces the `exe:` search modifier, which brings up the packages with exact or very similar names.
=> [FLORA-62] Search executable by name

app/cli/Main.hs, app/server/Main.hs, flora.cabal, src/core/Flora/Model/Job.hs, src/core/Flora/Model/PackageIndex/Update.hs, src/jobs-worker/FloraJobs/Runner.hs, src/jobs-worker/FloraJobs/Scheduler.hs, src/jobs-worker/FloraJobs/Types.hs, src/web/FloraWeb/Server.hs
This PR implements consistency checks at startup. For now they are quite rudimentary:
* Checks if the repo update job is queued, if not it's being enqueued
* Checks if all the expected package indexes are already provisioned in the database, if not it stops the server. You need to run `make db-provision`.
Example output:
```
SELECT "package_indexes"."repository" FROM "package_indexes"
2024-04-02 18:06:27 ATTENTION flora-server: Database validation failed: Expected package indexes: horizon.
make: *** [Makefile:5: start] Error 1
```
=> [NO-ISSUE] Implement database consistency checks at startup

changelog.d/553, src/core/Flora/Import/Package.hs, src/core/Flora/Import/Package/Types.hs
=> [FLORA-67] Log and re-import packages with zero dependencies

changelog.d/560, migrations/20240617215020_make_archive_checksum_nullable.sql, src/core/Flora/Import/Package.hs, src/core/Flora/Import/Package/Bulk.hs, src/core/Flora/Import/Types.hs, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Release/Types.hs, src/core/Flora/Model/Release/Update.hs, test/Flora/TestUtils.hs
The astute reader will notice that an IORef is used. It is because when we read the tarball, we encounter the JSON file of a release before the cabal file. As such, the release is not yet present in the database, so we store it in memory until we encounter the cabal file. Then we collect the hash and delete it from the in-memory map.
=> [FLORA-414] Store archive hashes

assets/css/2-components/1-navbar.css, assets/css/3-screens/1-package/1-package.css, assets/css/3-screens/1-package/4-compiler-badge.css, src/web/FloraWeb/Components/Navbar.hs
1. Readme area is shrinkable
2. Release tag on the right have adjustable width
3. Theme button in the header doesn't shrink on itself anymore
**Before**
---
**After**
=> [NO-ISSUE] Improve medium-sized layout on package detail page

assets/package.json
It have been automatically added by Yarn (runed in v1.22.22) when I've started the `watch-assets` task so, I think it should be added to the code base.
cf. https://yarnpkg.com/configuration/manifest#packageManager
=> Specify Yarn as the package manager in package.json

docs/package.json
I've forgot about the documentation's package.json when I made the PR #581  😬
=> [NO-ISSUE] Specify Yarn as the package manager in documentation's package.json

src/web/FloraWeb/Components/Navbar.hs, src/web/FloraWeb/Components/Utils.hs
- Add missing (empty) alt attribute on the theme toggle's images
- Add a semantic/accessible text label (with an `aria-label` attribute)
I manually added the aria-label attribute but since more ARIA attribute should probably added in the future, maybe [a package](https://hackage.haskell.org/package/lucid-aria) making all the ARIA attributes globally available into lucid templates could be an idea.
=> [NO-ISSUE] Add semantic label for light/dark theme toggle button

assets/.stylelintrc.json, assets/css/styles.css, assets/package.json, assets/yarn.lock
1. Remove the "stylelint-config-prettier" since it's [deprecated and no longer necessary](https://github.com/prettier/stylelint-config-prettier?tab=readme-ov-file#stylelint-config-prettier) since Stylelint v15 (the project were already in v15.x)
2. Upgrade `stylelint` `stylelint-config-standard` packages + Adding custom rules to match our current preferences
3. Add comments in the big import style.css file, clarifying the role of each main sections
=> [NO-ISSUE] Upgrade CSS lint tooling

assets/css/3-screens/2-categories.css
Remove hard-coded size (400x100px) to just let the cards content and grid container do the job
=> [NO-ISSUE] Avoid category cards from overflowing

src/web/FloraWeb/Pages/Templates/Screens/Home.hs
Update link to Cabal's documentation on the homepage: 
Replacing: https://cabal.readthedocs.io/en/stable/intro.html (404) to https://cabal.readthedocs.io/en/stable/getting-started.html
- ~~[ ] My PR is related to \<insert ticket number>~~ 
- ~~[ ] I have updated documentation in `./docs/docs` if a public feature has a behaviour change~~ Not necessary
=> [NO-ISSUE] Fix "Start with Cabal" link

.github/workflows/check-missing-fk-indexes.sh, .github/workflows/missing-fk-indexes.yml, changelog.d/605, environment.ci.sh, migrations/20241004135653_missing_fk_indexes.sql, scripts/missing-fk-indexes.sql
This PR adds a CI check to ensure that no index is missing for foreign keys. It's not a known fact that foreign keys do not automatically create indexes, despite their main usage being used for joins.
Shout-out to @marco44.
=> Add CI check for missing FK indexes

Makefile
Add docker-stop command to Makefile, improve comments
- Add a `docker-stop` command to only stop containers without removing them
- Clarify the comments/documentation
- ~~[ ] I have inserted my change and a link to this PR in the [CHANGELOG](https://github.com/flora-pm/flora-server/blob/development/CHANGELOG.md)~~ (no impact)
- ~~[ ] I have updated documentation in `./docs/docs` if a public feature has a behaviour change~~ (no impact)
=> Add “docker compose stop” task to Makefile

changelog.d/781, src/web/FloraWeb/Pages/Templates/Packages.hs
=> Render the HTML of readmes and changelogs

app/cli/Main.hs, changelog.d/783, flora.cabal, src/core/Flora/Environment.hs, src/core/Flora/Environment/Config.hs, src/core/Flora/Import/Package.hs, src/core/Flora/Import/Package/Bulk.hs, src/jobs-worker/FloraJobs/Runner.hs, test/Flora/TestUtils.hs, test/Main.hs
The queueing for parallel insertion seems to be at the source of problems when inserting large numbers of packages
=> Disable poolboy

migrations/20241014081932_create_affected_version_ranges.sql, migrations/20241116223018_add_index_on_release_version.sql, src/advisories/Advisories/Import.hs, src/advisories/Advisories/Model/Affected/Types.hs
This allows for greater flexiblity when it comes to declared versions that do not appear in the affected package repository
=> Store affected version ranges by version instead of release ID

cbits/categorise.dl
Fix minor typo in description of the `command-line` category. In particular, changed it from 
> Libraries to develope command-line interfaces
to
> Libraries to develop command-line interfaces
=> [NO-ISSUE] Fix minor typo in description ('develope' -> 'develop')

changelog.d/801, flora.cabal, src/web/FloraWeb/Server.hs
=> [FLORA-235] Re-enable prometheus metrics for http & process resources

assets/css/3-screens/1-package/5-security.css, changelog.d/805, docs/docs/search.md, flora.cabal, ghc-tags.yaml, src/advisories/Advisories/Model/Affected/Query.hs, src/core/Flora/Model/Release/Query.hs, src/search/Flora/Search.hs, src/web/FloraWeb/Components/PaginationNav.hs, src/web/FloraWeb/Links.hs, src/web/FloraWeb/Pages/Server/Search.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Screens/Search.hs
=> [FLORA-232] Advisory Search

cabal.project, flora.cabal, src/datatypes/Prometheus/Servant/HasEndpoint.hs, src/web/FloraWeb/Common/Guards.hs, src/web/FloraWeb/Pages/Routes/Sessions.hs, src/web/FloraWeb/Pages/Routes/Settings.hs, src/web/FloraWeb/Pages/Server/Sessions.hs, src/web/FloraWeb/Pages/Server/Settings.hs, src/web/FloraWeb/Pages/Templates.hs, src/web/FloraWeb/Server.hs
=> Use MultiVerb

app/server/Main.hs, changelog.d/flora-242, scripts/get-app-tables.sql
The messages look like this:
```
2025-03-07 12:13:41 ATTENTION flora-server: Database validation failed! Expected tables are missing: affected_packages, affected_version_ranges, blob_relations, categories, downloads, oddjobs, organisations, package_categories, package_components, package_group_packages, package_groups, package_indexes, package_publishers, packages, persistent_sessions, releases, requirements, security_advisories, user_organisation, users.
2025-03-07 12:13:41 ATTENTION flora-server: Database validation failed! Unexpected tables are present: toto.
```
=> Add database consistency checks

src/core/Flora/Model/Package/Query.hs, test/Flora/PackageSpec.hs, test/fixtures/Cabal/hackage/ghc-bignum-1.1.cabal, test/fixtures/Cabal/hackage/ghc-bignum-1.2.cabal, test/fixtures/Cabal/hackage/ghc-bignum-1.3.cabal
The transitive dependencies algorithm can get way too many results if it is not selective about which releases it is allowed to use. For the sake of simplicity, the latest release is always used.
Otherwise, we end up with results that look like:
| dependent_id                         | dependent_name | array_agg                                                                                                                       |
|--------------------------------------|----------------|---------------------------------------------------------------------------------------------------------------------------------|
| 01beb56b-23ed-bc5d-f406-a601954fa8dd | ghc-bignum     | [['haskell', 'ghc-prim', '>=0.5.1.0 && <0.10']] …
=> Use latest release version when computing transitive dependencies

changelog.d/865, src/core/Flora/Model/Package/Query.hs, src/web/FloraWeb/API/Routes/Packages.hs, src/web/FloraWeb/API/Server/Packages.hs
Implements #835.
A new route under `/api/experimental/packages/search/:packageNamePrefix` is added. It returns a vector of names of packages matching the prefix.
An example output:
```sh
$ curl http://localhost:8083/api/experimental/packages/search/text
["text-display","text-conversions","text-rope","text-manipulate","text-short","text","text-iso8601","text-zipper","text-icu"]⏎
```
=> [FLORA-835] Implement API route for searching packages by name prefix

assets/esbuild.config.js, assets/package.json, assets/yarn.lock
- Upgrade the esbuild postCSS loader to prevent further crash
- Replace the esbuild watch command to a custom one allowing changes from CSS sub files or style tokens tokes to trigger the rebuild
- Cleanup of js dependencies for the `assets` folder
- Remove unused packages
- Move used client side libraries (AlpineJS/htmx) from "devDependencies" to "dependencies"
=> Fix broken assets watch command

CHANGELOG.md, CONTRIBUTING.md, changelog.d/910, docker-compose.live-eventlog.yml, environment.live-eventlog.sh, environment.sh, flora.cabal, src/core/Flora/Environment/Config.hs, src/web/FloraWeb/Server.hs
[FLORA-257]
- add separate docker compose config (to avoid interference with existing one) with Grafana, Influxdb and `eventlog-live`.
- point it to dedicated socket file
- make app write live events into socket.
- provide separate environment for capturing live events.
- update CONTRIBUTING.md on how to use the feature.
=> [FLORA-257] Support capturing live events from flora-server

flora.cabal, src/web/FloraWeb/Components/Header.hs, src/web/FloraWeb/Components/Navbar.hs
=> Moved update theme function to navbar instead of toplevel html
