flora-pm/flora-server

flora.cabal, nix/pkgs.nix, src/FloraWeb/Templates/Pages/Packages.hs
add lucid-alpine code from upstream.
Now it buidls again.
=> Remove pkg-config, lower cabal bound, fix prometheus

.github/workflows/ci.yml
Add a caching step to the Nix CI
=> Add caching for Nix CI

src/FloraWeb/Templates/Pages/Home.hs
=> Fix github link on homepage

cbits/categorise.cpp, cbits/categorise.dl, src/Flora/Import/Categories/Tuning.hs, src/Flora/Model/Package/Query.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs, test/Flora/TestUtils.hs
=> Display categories on the package page

assets/css/app.css, assets/esbuild.config.js, assets/js/app.js, assets/package.json, assets/tailwind.config.js, assets/yarn.lock, src/FloraWeb/Templates/Layout/App.hs, src/FloraWeb/Templates/Pages/Packages.hs
This PR vendors AlpineJS and makes the frontend use HSL instead of Hex colours
Moreover, the "show all…" link is not displayed if all dependants or dependencies are here.
=> Vendor AlpineJS and use HSL instead of Hex

.github/workflows/backend.yml, .github/workflows/frontend.yml, assets/css/app.css
=> Add CI for the frontend elements

assets/package.json, src/FloraWeb/Templates/Pages/Packages.hs
* [Properly quote the cpx script](https://github.com/flora-pm/flora-server/commit/528ba24a4b995d4591d5f085ba121b32df8b99a4)
* [Fix comparison logic for showing the "show all…" link](https://github.com/flora-pm/flora-server/commit/890796f36cbd36c5061cc5eba8611f672fc94634)
=> Restore show all dependencies link

assets/css/app.css, design/stories/category-card.stories.js, flora.cabal, src/FloraWeb/Components/CategoryCard.hs, src/FloraWeb/Components/PackageListHeader.hs, src/FloraWeb/Server/Pages/Search.hs, src/FloraWeb/Templates/Packages/Dependencies.hs, src/FloraWeb/Templates/Packages/Dependents.hs, src/FloraWeb/Templates/Packages/Listing.hs, src/FloraWeb/Templates/Pages/Categories/Show.hs, src/FloraWeb/Templates/Pages/Search.hs
=> Unify the presentation style of package listings

assets/css/app.css, flora.cabal, migrations/20211106123053_create_releases.sql, src/Flora/Import/Package.hs, src/Flora/Model/Release.hs, src/Flora/Model/Release/Query.hs, src/FloraWeb/Client.hs, src/FloraWeb/Links.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Templates/Pages/Packages.hs
=> Add version links to the sidebar

nix/pin2.nix, shell.nix
this will make it build if the user runs make soufle and then make build. (and has the right version of glibc globally, but of course they'll know that 😉)
idk if this is worth metnioning in a changelog.
=> Upgrade soufle to 2.2 in shell

src/FloraWeb/Templates/Pages/Home.hs
=> Fix the About page contact paragraph

shell.nix
Add pg migration to shell to fix `make db-setup`
I don't think any of these are relevant
=> Add pg migration to shell to fix `make db-setup`

assets/css/app.css, deployment/flora.nginx, src/FloraWeb/Components/Navbar.hs, src/FloraWeb/Templates/Pages/Home.hs, src/FloraWeb/Templates/Pages/Packages.hs
=> Improve category cards css

Makefile, app/cli/CoverageReport.hs, deployment/flora.nginx, flora.cabal, fourmolu.yaml, src/Flora/Import/Package.hs, src/Flora/Model/Downloads.hs, src/Flora/Model/User.hs, src/FloraWeb/Components/Navbar.hs, src/FloraWeb/Components/PackageListItem.hs, src/FloraWeb/Links.hs, src/FloraWeb/Routes/Pages/Packages.hs, src/FloraWeb/Server.hs, src/FloraWeb/Templates/Admin.hs, src/FloraWeb/Templates/Error.hs
Disable MIME-type sniffing for assets
=> Disable MIME-type sniffing

assets/css/app.css, flora.cabal, src/Flora/Model/Package/Query.hs, src/Flora/Model/Package/Types.hs, src/Flora/Model/Release.hs, src/Flora/Model/Release/Orphans.hs, src/Flora/Model/Release/Query.hs, src/FloraWeb/Components/PackageListItem.hs, src/FloraWeb/Components/VersionListHeader.hs, src/FloraWeb/Components/VersionListItem.hs, src/FloraWeb/Links.hs, src/FloraWeb/Routes/Pages/Packages.hs, src/FloraWeb/Server/Guards.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Server/Pages/Sessions.hs, src/FloraWeb/Server/Utils.hs, src/FloraWeb/Templates/Packages/Dependents.hs, src/FloraWeb/Templates/Packages/Versions.hs, src/FloraWeb/Templates/Pages/Packages.hs
Display package versions in a more ergonomic way
=> Ergonomic display of versions

src/Flora/Model/Release/Query.hs, src/FloraWeb/Server/Pages/Packages.hs
=> Fix versions displaying

shell.nix
=> fix the of the nix shell entry welcome message

flora.cabal, src/Flora/Model/Package/Types.hs, test/Flora/TemplateSpec.hs, test/Flora/TestUtils.hs, test/Main.hs
Test the `ToHttpApiData` instance of `Namespace`.
=> Ensure the ToHttpApiData instance of Namespace is tested

migrations/20211106003401_create_packages.sql, migrations/20211106123053_create_releases.sql, migrations/20220326182257_create_latest_versions.sql, src/Flora/Import/Package.hs, src/Flora/Model/Category/Query.hs, src/Flora/Model/Package/Orphans.hs, src/Flora/Model/Package/Query.hs, src/Flora/Model/Package/Types.hs, src/Flora/Model/Package/Update.hs, src/Flora/Model/Release.hs, src/Flora/Model/Release/Orphans.hs, src/Flora/Model/Release/Query.hs, src/FloraWeb/Templates/Pages/Packages.hs, test/fixtures/Cabal/parallel.cabal
This PR moves the `synopsis` field to the `release` model.
=> Move synopsis to the release model

Makefile, app/cli/Main.hs, assets/css/app.css, cabal.project, flora.cabal, migrations/20220531232510_create_oddjobs.sql, migrations/20220605185406_add-html-column-to-releases.sql, shell.nix, src/Flora/Environment.hs, src/Flora/Environment/Config.hs, src/Flora/Environment/OddJobs.hs, src/Flora/Import/Package.hs, src/Flora/Model/Package/Types.hs, src/Flora/Model/Release.hs, src/Flora/Model/Release/Query.hs, src/Flora/OddJobs.hs, src/FloraWeb/Routes/Pages/Admin.hs, src/FloraWeb/Server.hs, src/FloraWeb/Server/Auth.hs, src/FloraWeb/Server/Logging.hs, src/FloraWeb/Server/Pages.hs, src/FloraWeb/Server/Pages/Admin.hs, src/FloraWeb/Server/Pages/Categories.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Server/Pages/Sessions.hs, src/FloraWeb/Templates/Admin.hs, src/FloraWeb/Templates/Pages/Packages.hs, test/Flora/OddJobSpec.hs, test/Flora/TestUtils.hs, test/Main.hs
=> Try add oddjobs

migrations/20211106123053_create_releases.sql, migrations/20220605185406_add-html-column-to-releases.sql, src/Flora/Import/Package.hs, src/Flora/Model/Release.hs, src/FloraWeb/Components/Navbar.hs, src/FloraWeb/Server/Pages/Admin.hs, src/FloraWeb/Templates/Pages/Packages.hs, src/FloraWeb/Templates/Types.hs
* Remove the `<h3>` in the release README
* Unify the release schema migrations
* Add the `description` field in the metadata of a release
=> Tweak descriptions and package readmes

app/server/Main.hs, src/Flora/Import/Categories/Tuning.hs, src/Flora/Model/Package/Query.hs, src/FloraWeb/Components/Navbar.hs, test/Flora/TestUtils.hs, test/Main.hs
=> Tweaking the schema

CONTRIBUTING.md, src/Flora/Search.hs, src/FloraWeb/Server/Pages/Search.hs, test/Flora/PackageSpec.hs, test/fixtures/Cabal/text-1.2.5.0.cabal, test/fixtures/Cabal/text-2.0.cabal
=> Add search test

cbits/categorise.dl, src/Flora/Import/Package.hs
=> Add more categories

.gitignore, migrations/20220531232510_create_oddjobs.sql
=> Unfuck odd jobs migration

cbits/categorise.dl, src/Flora/Search.hs
=> Add even more categories

.hlint.yaml, assets/css/app.css, assets/css/package-readme.css, assets/package.json, assets/yarn.lock, src/Flora/Model/Release/Query.hs, src/Flora/Model/User/Update.hs, src/FloraWeb/Templates.hs
Make `img`s inside `.package-readme` `inline-block`.
=> Make images in .package-readme inline-block

assets/css/package-readme.css
=> Support h3 and h4 heading in a release's readme

src/FloraWeb/Components/Navbar.hs, test/Flora/TestUtils.hs
Remove the login page from the navbar
=> Remove the login page from the navbar

flora.cabal, src/Data/Time/Orphans.hs, src/Flora/Model/Release/Update.hs, src/Flora/OddJobs.hs, src/Flora/OddJobs/Types.hs, src/Flora/ThirdParties/Hackage/API.hs, src/Flora/ThirdParties/Hackage/Client.hs, src/FloraWeb/Routes/Pages/Admin.hs, src/FloraWeb/Server/Pages/Admin.hs, src/FloraWeb/Templates/Admin.hs, src/FloraWeb/Templates/Pages/Packages.hs
Fetch, store and display release timestamps
=> Store and display release timestamp

migrations/20211106123053_create_releases.sql, src/Flora/Model/Release/Query.hs, src/FloraWeb/Server/Pages/Admin.hs
=> Only insert relevant releases in the jobs queue

src/Flora/Model/Package/Query.hs
=> Fix SQL query to fetch requirements

flora.cabal, src/Flora/Model/Package/Query.hs, src/Flora/Model/Package/Types.hs, src/Flora/OddJobs.hs, src/Flora/Publish.hs, src/Flora/Search.hs, src/FloraWeb/Server/Logging.hs, test/Flora/TestUtils.hs, test/Main.hs
Add logging and timing for some DB queries.
=> Insert logging for the duration of some DB queries

flora.cabal, src/FloraWeb/Components/Header.hs, src/FloraWeb/Routes.hs, src/FloraWeb/Server.hs, src/FloraWeb/Server/OpenSearch.hs
Fix #127
Implement an OpenSearch endpoint
=> Implement OpenSearch

assets/css/package-readme.css, src/Flora/OddJobs.hs, src/Flora/ThirdParties/Hackage/API.hs
Fix the colour of code blocks in light mode
=> Fix the colour of code blocks in light mode

CHANGELOG.md, cabal.project, flora.cabal
=> Prepare v1.0.0 release

assets/css/app.css, assets/css/package-readme.css, assets/css/variables.css, src/FloraWeb/Components/Header.hs, src/FloraWeb/Components/Navbar.hs, src/FloraWeb/Components/PackageListHeader.hs, src/FloraWeb/Components/PackageListItem.hs, src/FloraWeb/Components/VersionListItem.hs, src/FloraWeb/Templates/Packages/Dependencies.hs, src/FloraWeb/Templates/Packages/Versions.hs, src/FloraWeb/Templates/Pages/Categories/Index.hs, src/FloraWeb/Templates/Pages/Categories/Show.hs, src/FloraWeb/Templates/Pages/Home.hs, src/FloraWeb/Templates/Pages/Packages.hs, src/FloraWeb/Templates/Pages/Search.hs
=> [FLORA-199] Use CSS variables to split dark and light themes

CHANGELOG.md, assets/css/app.css
=> Readjust the size of the main title

CHANGELOG.md, CONTRIBUTING.md, assets/css/app.css, assets/css/variables.css, assets/package.json, assets/yarn.lock, design/stories/package-list--item.stories.js
fix #169
Search bars are now colourised when on-focus.
https://user-images.githubusercontent.com/15848443/192151194-b727f781-76a4-4b9d-955e-57cbc550cdb7.mp4
=> [FLORA-169] Colourise the search bars on focus

src/FloraWeb/Components/Header.hs, src/FloraWeb/Server/Pages/Packages.hs
Add OpenGraph metadata in package sub-pages
fix #216
=> [FLORA-216] Add OpenGraph metadata in package sub-pages

assets/css/app.css
Category links are now properly underlined in a package page
=> Fix category links' underline in package page

.github/mergify.yml, cbits/categorise.dl
Refine categorisation for some edge cases in Web, Maths and Game
=> [NO-ISSUE] Refine category normalisation

src/Flora/Import/Package/Bulk.hs
Size of a chunk is increased from 200 to 400
=> [NO-ISSUE] Increase chunk size for package import

CHANGELOG.md, flora.cabal
=> [NO-ISSUE] Prepare v1.0.4

.github/mergify.yml, .github/workflows/check-flora-tickets-in-prs.yaml, .github/workflows/check-ticket-in-prs.sh, CHANGELOG.md, CONTRIBUTING.md, README.md, assets/css/app.css, assets/css/variables.css, assets/package.json, assets/yarn.lock, cbits/categorise.dl, deployment/flora.nginx, design/stories/package-list--item.stories.js, flora.cabal, ghc-tags.yaml, src/Flora/Import/Package/Bulk.hs, src/FloraWeb/Components/Header.hs, src/FloraWeb/Components/Navbar.hs, src/FloraWeb/Server.hs, src/FloraWeb/Server/Auth.hs, src/FloraWeb/Server/Auth/Types.hs, src/FloraWeb/Server/Pages/Packages.hs
=> [NO-ISSUE] v1.0.4

CHANGELOG.md, assets/css/app.css, src/FloraWeb/Server.hs, src/FloraWeb/Templates/Error.hs
The right column will be easier to access on phone, as it will
not be hidden by the README body.
fix #233
=> [FLORA-233] Reorder the columns of the package view in mobile view

CHANGELOG.md, src/FloraWeb/Templates/Pages/Home.hs
=> [FLORA-235] Autofocus the search field on the home page

src/FloraWeb/Templates.hs
=> [NO-ISSUE] Refactor `FloraWeb.Templates.render`

default.nix, flake.lock, flake.nix, flora.cabal, nix/envparse.nix, nix/gitignoreSource.nix, nix/log-effectful.nix, nix/odd-jobs.nix, nix/pg-transact-effectful.nix, nix/pin.nix, nix/pin2.nix, nix/prometheus-client.nix, nix/prometheus-metrics-ghc.nix, nix/raven-haskell.nix, nix/servant-effectful.nix, nix/time-effectful.nix, nix/wai-middleware-heartbeat.nix, nix/wai-middleware-prometheus.nix
=> Enable flake support for development

CHANGELOG.md, assets/css/app.css, assets/css/release-changelog.css, assets/css/release-readme.css, assets/css/variables.css, flora.cabal, migrations/20221011215519_add_changelogs.sql, src/Flora/Import/Package.hs, src/Flora/Model/Release/Query.hs, src/Flora/Model/Release/Types.hs, src/Flora/Model/Release/Update.hs, src/Flora/OddJobs.hs, src/Flora/OddJobs/Render.hs, src/Flora/OddJobs/Types.hs, src/Flora/ThirdParties/Hackage/API.hs, src/Flora/ThirdParties/Hackage/Client.hs, src/FloraWeb/Links.hs, src/FloraWeb/Routes/Pages/Admin.hs, src/FloraWeb/Routes/Pages/Packages.hs, src/FloraWeb/Server.hs, src/FloraWeb/Server/Pages/Admin.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Templates/Admin.hs, src/FloraWeb/Templates/Packages/Changelog.hs, src/FloraWeb/Templates/Pages/Packages.hs, test/Flora/OddJobSpec.hs
Support release changelogs in the system
closes #147
=> [FLORA-147] Support release changelogs

CHANGELOG.md, migrations/20211113195849_create_dependents.sql, test/Flora/PackageSpec.hs
Packages are no longer kept as their own dependent
=> [FLORA-208] Packages are no longer kept as their own dependent

CHANGELOG.md, app/cli/DesignSystem.hs, assets/css/app.css, assets/css/variables.css, migrations/20220326182257_create_latest_versions.sql, src/Flora/Model/Package/Query.hs, src/Flora/Search.hs, src/FloraWeb/Components/PackageListItem.hs, src/FloraWeb/Templates/Packages/Dependencies.hs, src/FloraWeb/Templates/Packages/Dependents.hs, src/FloraWeb/Templates/Packages/Listing.hs, src/FloraWeb/Templates/Pages/Categories/Show.hs, src/FloraWeb/Templates/Pages/Search.hs
Licenses are displayed in package listing, and fixed versions are shown in green.
---
fix #185
=> [FLORA-185] Display license in package listings

CHANGELOG.md, assets/css/app.css, src/Distribution/Orphans.hs, src/Flora/Import/Package.hs, src/Flora/Model/Release/Types.hs, src/FloraWeb/Templates/Pages/Packages.hs
=> [FLORA-246] Display package flags

CHANGELOG.md, assets/css/release-readme.css, flora.cabal, src/FloraWeb/Templates/Haddock.hs, src/FloraWeb/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs, test/Flora/TestUtils.hs, test/fixtures/Cabal/filepath.cabal, test/fixtures/Cabal/relude.cabal
This PR renders the Description of releases when no README is available
=> [FLORA-137] Render description to HTML when there is no README

CHANGELOG.md, cbits/categorise.dl
---
Please remember to add the `hacktoberfest-accepted` label to this PR 😘 
Fixes #258
=> [FLORA-258] Add new categories: profiling, debugging and telemetry 🆕

.github/workflows/backend.yml, CHANGELOG.md, assets/css/release-readme.css
Fix leading whitespace in pre > code blocks by not putting padding around `code` blocks that are inside `pre` blocks.
=> [FLORA-264] Fix leading whitespace in pre > code blocks

.github/workflows/flakes.yml, flake.lock, flake.nix, flora.cabal, src/Flora/Import/Package.hs, src/Flora/Import/Package/Bulk.hs
It's actually a draft since it has the following shortcomings:
Results (on a 20-core CPU):
- `before`: 4745.19s user 916.19s system 144% cpu 57:59.78 total
- `after`: 6869.13s user 1557.62s system 619% cpu 22:39.85 total
=> [NO-ISSUE] Bulk speedup

.github/workflows/setup.sh, cabal.project, flora.cabal, src/Data/Password/Orphans.hs, src/Flora/Import/Package.hs, src/Flora/Import/Package/Bulk.hs, src/Flora/Model/Category/Types.hs, src/Flora/Model/Package/Component.hs, src/Flora/Model/Package/Types.hs, src/Flora/Model/PersistentSession.hs, src/Flora/Model/Release.hs, src/Flora/Model/Release/Types.hs, src/Flora/Model/Requirement.hs, src/Flora/Model/User.hs
=> [FLORA-289] Eliminate thunks

flora.cabal, src/Flora/Model/Release/Update.hs
Remove the fusion plugin globally and redundant constraints
=> [NO-ISSUE] Remove the fusion plugin globally and redundant constraints

CHANGELOG.md, app/cli/Main.hs, flora.cabal, src/Flora/Environment/OddJobs.hs, src/Flora/Import/Categories/Tuning.hs, src/Flora/Import/Package.hs, src/Flora/Import/Package/Bulk.hs, src/Flora/Import/Package/Types.hs, src/Flora/Model/Package/Component.hs, src/Flora/Model/Package/Types.hs, src/Flora/Model/Release/Types.hs, src/Flora/Model/Requirement.hs, src/Flora/OddJobs.hs, src/Flora/OddJobs/Types.hs, src/FloraWeb/Server.hs, test/Flora/TestUtils.hs
=> [FLORA-299] Enqueue package import jobs

CHANGELOG.md, assets/css/categories.css, assets/css/styles.css, cabal.project, src/FloraWeb/Components/CategoryCard.hs, src/FloraWeb/Components/Navbar.hs, src/FloraWeb/Templates/Pages/Packages.hs
=> Drop Tailwind: Part 3

CHANGELOG.md, migrations/20221227125533_add_oddjobs_payload_index.sql
Add a GIN index on the payload jsonb for oddjobs
fix #311
=> [FLORA-311] Add a GIN index on the payload jsonb for oddjobs

CHANGELOG.md, src/Flora/OddJobs.hs
=> [NO-ISSUE] Don't fail the upload time job when the package doesn't exist

CHANGELOG.md, assets/css/package.css, assets/css/release-readme.css, assets/css/styles.css
=> [NO-ISSUE] Re-organise columns on smaller screens

flake.lock, flake.nix
=> [NO-ISSUE] nix flake update

CHANGELOG.md, flake.nix, src/FloraWeb/Components/Header.hs, src/FloraWeb/Components/Navbar.hs
=> [FLORA-320] Respect manual override of system theme

CHANGELOG.md, src/Flora/Model/Package/Query.hs, src/Flora/Model/Package/Types.hs, src/Flora/Search.hs, src/FloraWeb/Components/PaginationNav.hs, src/FloraWeb/Links.hs, src/FloraWeb/Routes/Pages/Packages.hs, src/FloraWeb/Server/Pages/Packages.hs, src/FloraWeb/Templates/Packages.hs, src/FloraWeb/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs
=> [FLORA-322] Paginate reverse dependencies page

flake.lock, flake.nix, src/Flora/Import/Package/Bulk.hs
see if this builds, I couldn't find streamly-core on hacakge
=>  Add streamly core tru flake input 

CHANGELOG.md, assets/css/styles.css, assets/css/variables.css, assets/tailwind.config.js, src/web/FloraWeb/Templates/Pages/Home.hs
=> [FLORA-340] Add buttons to the main page for ghcup and cabal

CHANGELOG.md, Makefile, flora.cabal, migrations/20230216221827_add_metadata_to_packages.sql, src/core/Flora/Import/Package.hs, src/core/Flora/Model/Category/Query.hs, src/core/Flora/Model/Job.hs, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Model/Package/Update.hs, src/jobs-worker/FloraJobs/Runner.hs, src/jobs-worker/FloraJobs/Scheduler.hs, src/jobs-worker/FloraJobs/ThirdParties/Hackage/API.hs, src/jobs-worker/FloraJobs/ThirdParties/Hackage/Client.hs, src/web/FloraWeb/Server/Pages/Admin.hs, test/Flora/PackageSpec.hs, test/fixtures/Cabal/PBKDF2.cabal
=> [FLORA-319] Store deprecation information for packages

CHANGELOG.md, assets/css/package.css, flora.cabal, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Model/Package/Update.hs, src/jobs-worker/FloraJobs/Runner.hs, src/jobs-worker/FloraJobs/ThirdParties/Hackage/API.hs, src/jobs-worker/FloraJobs/ThirdParties/Hackage/Client.hs, src/web/FloraWeb/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs
Display deprecation information on the package page
=> [FLORA-319] Display deprecation information on the package page

src/core/Flora/Import/Package.hs, src/web/FloraWeb/Server.hs, src/web/FloraWeb/Server/Pages/Admin.hs
I don't know if you want this, but just in case ... :)
Leaving `HasCallStack` and the `Time` effect in there might well have been deliberate.
=> [NO-ISSUE] Zap some warnings

CONTRIBUTING.md, environment.sh
=> [NO-ISSUE] Fix some typos

flake.nix
override seems to no longer exist
=> use .extend instead of .override

migrations/20230805154456_remove_package_metadata.sql, src/core/Flora/Import/Package.hs, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Model/Package/Update.hs, src/jobs-worker/FloraJobs/Runner.hs, src/web/FloraWeb/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs, test/Flora/TestUtils.hs, test/Main.hs
Remove the `metadata` field from the Package table.
=> [FLORA-409] Remove metadata package field

migrations/20211106003401_create_packages.sql, migrations/20211106123053_create_releases.sql, migrations/20220326182257_create_latest_versions.sql, migrations/20230216221827_add_metadata_to_packages.sql, migrations/20230407180816_exclude_deprecated_releases_from_latest_versions.sql, migrations/20230623168754_add_repo_to_release.sql, migrations/20230805154456_remove_package_metadata.sql, src/core/Flora/Import/Package.hs, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Release/Query.hs, src/core/Flora/Model/Release/Types.hs, src/core/Flora/Model/Release/Update.hs, src/orphans/Distribution/Orphans.hs, src/web/FloraWeb/Server/Pages/Packages.hs, src/web/FloraWeb/Templates/Packages.hs, src/web/FloraWeb/Templates/Pages/Packages.hs, test/Flora/PackageSpec.hs
=> [FLORA-410] Remove release metadata field

CHANGELOG.md, assets/css/styles.css
I have worked on the task detailed at #418 , please see the attached images below compared to what was shown in the task and merge if you think my fix is satisfactory.
I have also updated the `CHANGELOG.md` to reflect the change and link to the pull request.
This is my first pull request for an open source project and I have tried to keep to the guidelines provided as best as I could, I apologize if I have made any errors!
=> [FLORA-418] Fixed text color for header and button in login page

flake.lock, flake.nix
=> [NO-ISSUE][fix] pin souffle once and for all to 2.3

CHANGELOG.md, assets/css/styles.css, src/core/Flora/Import/Package/Bulk.hs, src/jobs-worker/FloraJobs/Runner.hs, src/web/FloraWeb/Pages/Templates/Pages/Home.hs
A container is now tasked with dealing with the margins and the size of the search bar, divider line and buttons. These elements will simply fill their containers.
=> [FLORA-429] Fix the margins of the main search bar

CHANGELOG.md, assets/css/3-screens/1-package/1-package.css, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Release/Query.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Pages/Packages.hs
=> [FLORA-438] Colourise in red deprecation markers on the package page

.github/workflows/backend.yml
=> [NO-ISSUE] Use haskell-action/setup

CHANGELOG.md, Makefile, app/cli/Main.hs, flora.cabal, migrations/20231210110311_add_description_to_package_index.sql, src/core/Flora/Model/PackageIndex/Types.hs, src/core/Flora/Model/PackageIndex/Update.hs, src/web/FloraWeb/Components/PackageListHeader.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Templates/Screens/Search.hs, test/Flora/ImportSpec.hs, test/Main.hs
=> [FLORA-448] Add description field in package index

.github/workflows/linting.yml, .gitignore, CHANGELOG.md, assets/css/3-screens/1-package/1-package.css, flora.cabal, migrations/20240225155408_add_buildtype_to_releases.sql, src/core/Flora/Import/Package.hs, src/core/Flora/Model/Release/Types.hs, src/datatypes/Distribution/Orphans/BuildType.hs, src/web/FloraWeb/Components/Pill.hs, src/web/FloraWeb/Components/Utils.hs, src/web/FloraWeb/Pages/Templates/Packages.hs
Packages with the `Custom` build type will have an orange badge of shame next to the "Installation" h3 title:
=> [FLORA-512] Add badge component for custom build type

assets/css/3-screens/5-settings/1-dashboard.css, assets/css/styles.css, src/core/Flora/Environment.hs, src/web/FloraWeb/API/Server.hs, src/web/FloraWeb/API/Server/Packages.hs, src/web/FloraWeb/Common/Auth.hs, src/web/FloraWeb/Common/Auth/Types.hs, src/web/FloraWeb/Common/Guards.hs, src/web/FloraWeb/Components/Navbar.hs, src/web/FloraWeb/Pages/Routes.hs, src/web/FloraWeb/Pages/Routes/Admin.hs, src/web/FloraWeb/Pages/Routes/Packages.hs, src/web/FloraWeb/Pages/Routes/Settings.hs, src/web/FloraWeb/Pages/Server.hs, src/web/FloraWeb/Pages/Server/Admin.hs, src/web/FloraWeb/Pages/Server/Categories.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Server/Search.hs, src/web/FloraWeb/Pages/Server/Sessions.hs, src/web/FloraWeb/Pages/Server/Settings.hs, src/web/FloraWeb/Pages/Templates/Error.hs, src/web/FloraWeb/Pages/Templates/Screens/Settings.hs, src/web/FloraWeb/Pages/Templates/Types.hs, src/web/FloraWeb/Server.hs, src/web/FloraWeb/Session.hs, src/web/FloraWeb/Types.hs
=> [NO-ISSUE] Reword authentication

app/cli/DesignSystem.hs, flora.cabal, migrations/20230407180816_exclude_deprecated_releases_from_latest_versions.sql, migrations/20240315155250_create_elem_rating_type.sql, src/core/Flora/Model/Package/Query.hs, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Search.hs, src/web/FloraWeb/Components/PackageListItem.hs, src/web/FloraWeb/Components/PaginationNav.hs, src/web/FloraWeb/Links.hs, src/web/FloraWeb/Pages/Server/Search.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Screens/Search.hs
=> [FLORA-62] Fix the SQL queries for executable search

cabal.project, src/core/Flora/Model/Release/Types.hs, src/web/FloraWeb/Client.hs, test/Flora/ImportSpec.hs, test/Flora/PackageSpec.hs, test/Flora/SearchSpec.hs, test/Flora/TestUtils.hs, test/Main.hs
This PR introduces the necessary infrastructure to start writing tests that require random packages, and introduces some search tests.
=> [FLORA-64] Test search modifiers

CHANGELOG.md, src/web/FloraWeb/Components/Navbar.hs
=> [NO-ISSUE] Add documentation link to navbar

CHANGELOG.md, Makefile, cabal.project.repositories, docs/docs/namespaces.md
This PR adds a namespace for Horizon
=> [FLORA-498] Add @horizon namespace

app/cli/Main.hs, cabal.project, changelog.d/564, flora.cabal, src/core/Flora/Model/BlobIndex/Update.hs, src/core/Flora/Publish.hs, src/core/Flora/Tracing.hs, src/jobs-worker/FloraJobs/Runner.hs, src/web/FloraWeb/API/Server/Packages.hs, src/web/FloraWeb/Common/Guards.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Server.hs, src/web/FloraWeb/Types.hs
This PR lays the groundwork to use tracing with zipkin
=> [FLORA-214] Implement tracing with zipkin

changelog.d/567, flora.cabal, src/core/Flora/Model/Release/Query.hs
=> [NO-ISSUE] Sort and limit the amount of releases in the DB instead of Flora

CHANGELOG.md, flora.cabal
This is a hotfix release that considerably improves the first loading of package pages.
=> Prepare v1.0.20

assets/yarn.lock
Update `caniuse-lite` to 1.0.30001667
=> frontend: Update caniuse-lite

.github/workflows/check-duplicate-indexes.sh, .github/workflows/check-missing-fk-indexes.sh, .github/workflows/duplicate-indexes.yaml, migrations/20241004135653_missing_fk_indexes.sql, migrations/20241008193658_drop_redundant_indexes.sql, scripts/duplicate-indexes.sql
Following up #605, this PR adds a check in CI for duplicate / overlapping indexes.
=> Add check for duplicate indexes in CI

CONTRIBUTING.md
People do not need to build the image, it's automatically uploaded in GitHub.
=> Improve docker guide

deployment/flora.nginx
=> Flora nginx security

changelog.d/778, flora.cabal, src/core/Flora/Import/Package.hs, src/core/Flora/Import/Package/Bulk.hs, src/core/Flora/Publish.hs
=> Add more logging statements when importing packages

cabal.project, flora.cabal, test/Main.hs
=> Add a test reporter

app/cli/DesignSystem.hs, assets/css/2-components/11-advisory-list-item.css, src/advisories/Advisories/Model/Affected/Query.hs, src/advisories/Advisories/Model/Affected/Types.hs, src/web/FloraWeb/Components/AdvisoryListItem.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Screens/Search.hs
Search results will also show qualified package names associated with an advisory
=> Adapt advisories listing for search

changelog.d/813, src/core/Flora/Import/Package.hs
=> Add new GHC versions

.github/workflows/backend.yml, .github/workflows/changelog.yaml, .github/workflows/docker-image.yml, .github/workflows/duplicate-indexes.yaml, .github/workflows/frontend.yml, .github/workflows/linting.yml, .github/workflows/missing-fk-indexes.yml, .github/workflows/setup.sh, .github/workflows/test-docker-image.yml, cabal.project, changelog.d/817, src/web/FloraWeb/Components/PaginationNav.hs
=> Do not wrongly include "Nothing" as a query param to dependents listing

Makefile, assets/.stylelintignore, assets/css/prism.css, assets/css/styles.css, assets/esbuild.config.js, assets/js/prism.js, changelog.d/819, src/core/Flora/Environment/Config.hs, src/web/FloraWeb/Pages/Templates.hs, test/Flora/PackageSpec.hs, test/fixtures/Cabal/hackage/hyperbole-0.3.6.cabal
This PR includes PrismJS to highlight code in READMEs
=> Include prismJS to highlight code in the READMEs

CHANGELOG.md, changelog.d/817, changelog.d/819, flora.cabal
=> Prepare release 1.0.24

app/cli/Main.hs, flora.cabal, src/core/Flora/Environment.hs, src/core/Flora/Import/Package.hs, src/core/Flora/Model/BlobIndex/Query.hs, src/core/Flora/Model/Category/Types.hs, src/core/Flora/Model/Component/Types.hs, src/core/Flora/Model/Package/Types.hs, src/core/Flora/Model/PackageIndex/Types.hs, src/core/Flora/Model/PersistentSession.hs, src/core/Flora/Model/Requirement.hs, src/core/Flora/Model/User.hs, src/core/Flora/Monitoring.hs, src/datatypes/Advisories/AffectedVersionRange/Orphans.hs, src/jobs-worker/FloraJobs/Runner.hs, src/jobs-worker/FloraJobs/ThirdParties/Hackage/API.hs, src/jobs-worker/FloraJobs/Types.hs, src/web/FloraWeb/API/Routes/Packages/Types.hs, src/web/FloraWeb/Common/Auth.hs, src/web/FloraWeb/Pages/Templates/Packages.hs, src/web/FloraWeb/Pages/Templates/Types.hs, test/Flora/TestUtils.hs
=> [FLORA-245] Remove most RecordWildcards

src/core/Flora/Normalise.hs, test/Flora/CategorySpec.hs
=> [FLORA-244] More category normalisation tests

.cirrus.yml, .github/workflows/backend.yml
=> Setup cirrus ci configuration

changelog.d/864, scripts/start-tmux.sh
The improved tmux script can now be nested safely.
It works with zsh inside docker (support for other shells is a non-goal).
I have removed the `sleep` instruction and have not seen any issues.
=> [NO-ISSUE] Improve tmux script

flora.cabal, src/web/FloraWeb/Common/Auth/Types.hs, src/web/FloraWeb/Common/OpenSearch.hs, src/web/FloraWeb/Components/PaginationNav.hs
=> Vendor the xml-conduit-writer package

.github/workflows/setup.sh, app/cli/DesignSystem.hs, assets/css/2-components/6-secondary-search.css, docs/yarn.lock, flora.cabal, src/core/Flora/Environment.hs, src/core/Flora/Model/Package/Types.hs, src/web/FloraWeb/Components/Icons.hs, src/web/FloraWeb/Components/Utils.hs, src/web/FloraWeb/Feed/Routes.hs, src/web/FloraWeb/Feed/Server.hs, src/web/FloraWeb/Feed/Templates.hs, src/web/FloraWeb/Pages/Routes/Packages.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Templates.hs, src/web/FloraWeb/Pages/Templates/Types.hs, src/web/FloraWeb/Routes.hs, src/web/FloraWeb/Server.hs
https://github.com/user-attachments/assets/64df57f2-4062-4e9d-8833-1ab98124dd3d
=> Flora 251 package feed building interface

src/jobs-worker/FloraJobs/Runner.hs, src/web/FloraWeb/Feed/Templates.hs
=> Fix the re-enqueueing of the RefreshIndex job

src/core/Flora/Model/Release/Query.hs, src/web/FloraWeb/Pages/Server/Packages.hs, src/web/FloraWeb/Pages/Templates.hs, test/Flora/PackageSpec.hs
=> Replaced maximumBy on version usage with SQL query

assets/css/1-core/1-reset.css, assets/css/2-components/17-skip-link.css, assets/css/styles.css, flora.cabal, src/web/FloraWeb/Components/Header.hs, src/web/FloraWeb/Components/SkipLink.hs, src/web/FloraWeb/Pages/Templates.hs
Add a quick access to main content
- https://www.a11yproject.com/posts/skip-nav-links/
- https://a11y-guidelines.orange.com/en/articles/skip-links-best-practices/
=> Add skip link to main content
